services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: online-shop
      MYSQL_USER: user
      MYSQL_PASSWORD: 1235
    ports:
        - "3306:3306"