# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/online-shop
spring.datasource.username=user
spring.datasource.password=1235

# Keycloak JWT Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/online-shop

# Keycloak Admin API (DB -> Keycloak profile sync)
keycloak.admin.server-url=http://localhost:8081
keycloak.admin.realm=online-shop
keycloak.admin.client-id=shop-backend
keycloak.admin.client-secret=9415MIA8mva8cdhvQlRBCao1npmqPwRE

# Cloudinary
cloudinary.cloud-name=ddjp97kir
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# Spring Actuator
management.endpoints.access.default=unrestricted
