# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/online-shop
spring.datasource.username=user
spring.datasource.password=1235

# Keycloak JWT Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/online-shop

# Keycloak Admin API (DB -> Keycloak profile sync)
keycloak.admin.server-url=http://localhost:8081
keycloak.admin.realm=online-shop
keycloak.admin.client-id=shop-backend
keycloak.admin.client-secret=9415MIA8mva8cdhvQlRBCao1npmqPwRE

# Stripe (replace with your test keys)
stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=http://localhost:4200/checkout/success
stripe.cancel-url=http://localhost:4200/checkout/cancel
stripe.currency=RON
stripe.vat-rate=0.19
stripe.flat-shipping-amount=25.00

#ngrok https://uncannily-unlifting-vonda.ngrok-free.dev
# Cloudinary
cloudinary.cloud-name=ddjp97kir

# Spring Actuator
management.endpoints.access.default=unrestricted

# Seeders
seeders.enabled=true
